# Generated by Django 5.1 on 2024-09-02 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_course_remove_user_password_user_age_user_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='password_hash',
            new_name='password',
        ),
    ]
