# Generated by Django 5.1 on 2024-09-05 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_user_created_at_remove_user_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='workout_goal',
            field=models.CharField(blank=True, choices=[('Muscle Gain', 'Muscle Gain'), ('Fat Loss', 'Fat Loss'), ('Healthy Living', 'Healthy Living')], max_length=20, null=True),
        ),
    ]
