# Generated by Django 5.1 on 2024-09-06 19:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_user_workout_goal'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='preffer_target_area',
            field=models.CharField(choices=[('Arm', 'Arm'), ('Back', 'Back'), ('Chest', 'Chest'), ('Shoulders', 'Shoulders'), ('Legs', 'Legs'), ('Glutes', 'Glutes'), ('Full Body', 'Full Body'), ('Abdomen', 'Abdomen')], default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='workoutplan',
            name='target_area',
            field=models.CharField(choices=[('Arm', 'Arm'), ('Back', 'Back'), ('Chest', 'Chest'), ('Shoulders', 'Shoulders'), ('Legs', 'Legs'), ('Glutes', 'Glutes'), ('Full Body', 'Full Body'), ('Abdomen', 'Abdomen')], max_length=255),
        ),
    ]
