# Generated by Django 5.1 on 2024-09-06 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_user_preffer_target_area_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='preffer_target_area',
            new_name='muscle_groups',
        ),
    ]
